### PR TITLE
feat: add global option

### PR DESCRIPTION
**Pull request by jd1378**
this PR adds `global` option to module which controls the global registration of the icon components

### CODE REVIEW

**Comment by KnifeFed** [comment]
I'm a bit confused as to what this does exactly. How does registering globally or not differ and what are the implications for the user?

**Comment by jd1378** [comment]
well this is confusing for me as well 😅
the important takeaway for me, as mentioned in the readme, is that when this is true, it generates a chunk in the output for each icon. so for example if you have 1000 icons, it will generate 1000 files, even if you are not using all 1000 icons. but then setting it to false, only generates chunks for icons that you use.

since I couldn't determine if this is a breaking change for someone relying on it out there somehow, I did not set it to false by default.

but you probably almost always want to set it to false, or at least this is what I decided to do for myself.

I hope this helps

**Comment by KnifeFed** [comment]
Ah, I see. So as long as I only auto-import SVG's I'll actually use, this setting is irrelevant?

**Comment by KnifeFed** [comment]
Right, I mean if the `autoImportPath` only contains SVG's that are used, the setting doesn't matter.

**Comment by jd1378** [comment]
yeah

**Comment by jd1378** [comment]
@KnifeFed I found `global` in docs today, if you want to read: https://nuxt.com/docs/guide/directory-structure/components#dynamic-components

**Comment by KnifeFed** [comment]
Ah, that makes it a bit clearer, thanks!

**Pull request merged**
